version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-app/
    overwrite: yes
permissions:
  - object: /home/ubuntu/django-app/scripts/
    mode: 775
    type: 
      - file 
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      runas: root 
