version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-app/
    overwrite: yes
permissions:
  - object: /home/ubuntu/django-app/scripts/
    mode: 775
    type: 
      - file 
      - directory
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

